### ISSUE TITLE
为什么index.html文件要写在public目录下？

### ISSUE THREAD

**Issue by wongben** [xlsdg/dva-antd-mobile-starter#1]
![image](https://cloud.githubusercontent.com/assets/1499531/21922050/2ab0bac4-d9a7-11e6-8f75-defdcb138215.png)
为什么我写在src目录下查找不到？
搜索了全局文件，也没见配置的地方啊。。。。求解

**Comment by xlsdg** [comment]
这是新的 [dva](https://github.com/dvajs/dva-cli) 脚手架生成的目录结构。

**Comment by wongben** [comment]
哦，刚才看了文档，是roadhog的约定，谢谢
