### ISSUE TITLE
你配置的server.js 用不来 不知道是我使用的问题 还是什么问题

### ISSUE THREAD

**Issue by GGBO0M** [xlsdg/dva-antd-mobile-starter#12]

**Comment by GGBO0M** [comment]
![image](https://user-images.githubusercontent.com/23025550/34336645-d5aa6fb8-e993-11e7-9b84-54bea58b48c8.png)
![image](https://user-images.githubusercontent.com/23025550/34336652-e544766c-e993-11e7-9172-b5c572bef9ac.png)
![image](https://user-images.githubusercontent.com/23025550/34336670-025af5d2-e994-11e7-8269-bc18c2da0104.png)
我在使用getJson接口传入了url 和 data  返回的结果 是一个对象 还报一个Access-Control-Allow-Origin的错误 但是 NetWork 中显示 我这个接口返回200 成功了

**Comment by GGBO0M** [comment]
希望你在项目中加一个简单的使用例子，方便理解一下

**Comment by GGBO0M** [comment]
![image](https://user-images.githubusercontent.com/23025550/34340307-9976bec4-e9bc-11e7-8879-a0c86dddcb09.png)
我将你的这个方法改成了async  就好了，checkCode方法感觉没啥用，不知道为何要在返回的data中查看code？还有你Axios中CancelToken干啥用的? 看了文档是用来取消的请求， 不过不清楚具体使用场景是啥，有用吗？ 一定得配上吗？

**Comment by xlsdg** [comment]
只是一个示例，不一定要按示例代码来，结合实际情况来使用。
