### ISSUE TITLE
android企业微信后退不正常

### ISSUE THREAD

**Issue by xiaochunyong** [xlsdg/dva-antd-mobile-starter#4]
你好~  我有个问题想请教一下~~

我用android手机打开企业微信 - 从会话消息中点开链接( https://xlsdg.github.io/dva-antd-mobile-starter/ ) - 点击页面1 - 点击页面2 -   在页面2中按android返回键，正常返回到页面1

但是我clone代码在本机npm start 点击页面1, 点击页面2  返回  直接到了消息会话界面~~  这是什么原因啊~

**Comment by xlsdg** [comment]
你的邮件我已经收到了，只是没来得及回复。初步感觉是会不会跟你的URL有关系，或者是 `npm run start` 启动的是调试模式，而线上是编译之后的文件，暂时只是猜测。

**Comment by xiaochunyong** [comment]
我也尝试过npm run build方式部署过去, 并且我在antdesign官网找了一个设计的示例, 有一个也是可以正常的, 但是它是多entry的方式.  这个问题我找了好久一直没找到原因, 如果您有时间, 可以帮我看看嘛~ 谢谢~

**Comment by xlsdg** [comment]
我这边本地开调试，在个人微信里面是正常的。暂时没有企业微信提供测试，没法定位问题，可能是企业微信的容器 BUG。

**Comment by xiaochunyong** [comment]
是的, 个人微信没有问题, 只有android的企业微信有这个问题.  (如果有需要, 我可以把您加进来~~  哈哈. )
我已经向企业微信反馈这个问题了, 希望能得到解决~~  谢谢
