### ISSUE TITLE
使用antd的Icon图标，控制台会报错

### ISSUE THREAD

**Issue by l745230** [xlsdg/dva-antd-mobile-starter#5]
Icon props.type is invalid, have you set svg-sprite-loader correctly? see https://goo.gl/kN8oiw
![image](https://user-images.githubusercontent.com/15940920/29697879-60e78e64-8984-11e7-8e72-c9edb859b06b.png)

**Comment by l745230** [comment]
![image](https://user-images.githubusercontent.com/15940920/29697998-097e7c90-8985-11e7-95d7-21256adfbfdc.png)
看了一下，demo启动起来也是报错，是否因为使用了webpack.config.js，导致.roadhogrc.js中的svgSpriteLoaderDirs设置无效了呢？

**Comment by xlsdg** [comment]
最近升级了 `roadhog` 导致的。

https://github.com/sorrycc/roadhog/issues/372

https://github.com/sorrycc/roadhog/issues/345

https://github.com/sorrycc/roadhog/issues/343

**Comment by xlsdg** [comment]
暂时先用这个历史版本吧 https://github.com/xlsdg/dva-antd-mobile-starter/commit/541333bd8d8b0fffa290d9acdbe305733608979e

**Comment by xlsdg** [comment]
已更新 antd-mobile 到 2.x
